TareasCompletadas/Models/ErrorViewModel.cs
namespace TareasCompletadas.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TareasCompletadas/Models/TaskHistorial.cs
using System.ComponentModel.DataAnnotations;

namespace TareasCompletadas.Models
{
    public class TaskHistorial
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public  DateTime FechaEntrega { get; set; }
        public bool IsCompleted { get; set; } 
        public DateTime FechaCreacion { get; set; }
        

    }
}

TareasCompletadas/Models/TaskItem.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace TareasCompletadas.Models
{
    public class TaskItem
    {
        public int Id{ get; set; }
        [Required]
        public string Titulo{ get; set; }
        [Required]
        [MaxLength(200)]
        public string Descripcion{ get; set; }
        private DateTime _fechaEntrega;
        private bool _isCompleted;

        public DateTime FechaEntrega
        {
            get { return _fechaEntrega; }
            set { _fechaEntrega = value; }
        }

        public bool IsCompleted
        {
            get { return _isCompleted; } //Propiedad publica para acceder al estado de completado
            set
            {
                if (_isCompleted != value) //Comprobar si el valor esta cambiando
                {
                    _isCompleted = value; //Establecer el valor de completado 
                    if (_isCompleted)
                    {
                        _fechaEntrega = DateTime.Now; //Si se marca como completado, actualizar la fecha de entrega
                    }
                }
            }
        }
    }
}

TareasCompletadas/Controllers/TaskItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Rotativa.AspNetCore;
using TareasCompletadas.Data;
using TareasCompletadas.Models;

namespace TareasCompletadas.Controllers
{
    public class TaskItemController : Controller
    {
        private readonly TaskContext _context;

        public TaskItemController(TaskContext context)
        {
            _context = context;
        }

        // GET: TaskItem
        public async Task<IActionResult> Index()
        {
            ViewBag.TareasIncompletas = await _context.Tasks.Where(p => !p.IsCompleted).ToListAsync(); //Recupera todas las tareas incompletas de la base de datos y las almcacena en un viewbag
            ViewBag.TareasCompletadas = await _context.Tasks.Where(p => p.IsCompleted).ToListAsync(); //Recupera todas las tareas completas de la base de datos y las almcacena en un viewbag


              return _context.Tasks != null ? 
                          View(await _context.Tasks.ToListAsync()) :
                          Problem("Entity set 'TaskContext.Tasks'  is null.");
        }

        // GET: TaskItem/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Tasks == null)
            {
                return NotFound();
            }

            var taskItem = await _context.Tasks
                .FirstOrDefaultAsync(m => m.Id == id);
            if (taskItem == null)
            {
                return NotFound();
            }

            return View(taskItem);
        }

        // GET: TaskItem/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TaskItem/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Titulo,Descripcion,FechaEntrega,IsCompleted")] TaskItem taskItem)
        {
            var TaskHistorial = new TaskHistorial
            {
                Id = taskItem.Id,
                Titulo = taskItem.Titulo,
                Descripcion = taskItem.Descripcion,
                FechaEntrega = taskItem.FechaEntrega,
                FechaCreacion = DateTime.Now,
                IsCompleted = taskItem.IsCompleted,
            };

            if (ModelState.IsValid)
            {
                _context.Add(taskItem);
                _context.Historial.Add(TaskHistorial);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(taskItem);
        }

        // GET: TaskItem/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Tasks == null)
            {
                return NotFound();
            }

            var taskItem = await _context.Tasks.FindAsync(id);
            if (taskItem == null)
            {
                return NotFound();
            }
            return View(taskItem);
        }

        // POST: TaskItem/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Titulo,Descripcion,FechaEntrega,IsCompleted")] TaskItem taskItem)
        {
            if (id != taskItem.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(taskItem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TaskItemExists(taskItem.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(taskItem);
        }

        // GET: TaskItem/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Tasks == null)
            {
                return NotFound();
            }

            var taskItem = await _context.Tasks
                .FirstOrDefaultAsync(m => m.Id == id);
            if (taskItem == null)
            {
                return NotFound();
            }

            return View(taskItem);
        }

        // POST: TaskItem/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Tasks == null)
            {
                return Problem("Entity set 'TaskContext.Tasks'  is null.");
            }
            var taskItem = await _context.Tasks.FindAsync(id);
            if (taskItem != null)
            {
                _context.Tasks.Remove(taskItem);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TaskItemExists(int id)
        {
          return (_context.Tasks?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        public async Task<IActionResult> Historial()
        {
            return View(await _context.Historial.ToListAsync());
        }

        public async Task<IActionResult> ImprimirPDF(int id)
        {
            var tarea = await _context.Tasks.FindAsync(id);
            return new ViewAsPdf("ImprimirPDF", tarea)
            {
                FileName = $"Tarea.pdf",
                PageOrientation = Rotativa.AspNetCore.Options.Orientation.Portrait,
                PageSize = Rotativa.AspNetCore.Options.Size.A4
            };
        }
    }
}

TareasCompletadas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TareasCompletadas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TareasCompletadas.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid text-center">
                Administrador de tareas
            </div>
        </nav>
    </header>
    <div class="container" >
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TareasCompletadas - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TareasCompletadas/Views/TaskItem/Create.cshtml
@model TareasCompletadas.Models.TaskItem

@{
    ViewData["Title"] = "Create";
}

<section class="align-items-center">
    <div class="row justify-content-center">
        <div class="col-md-4">
            <div class="card-body p-md-5 mx-md-4 border border-dark rounded">

                <div class="text-center">
                    <i class="bi bi-file-earmark-plus" style="font-size: 5rem; color:cadetblue"></i>
                    <h4 class="mt-1 mb-5 pb-1">Agregar tarea</h4>
                </div>
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group mt-3">
                        <label asp-for="Titulo" class="form-label"></label>
                        <input asp-for="Titulo" class="form-control" />
                        <span asp-validation-for="Titulo" class="text-danger"></span>
                    </div>
                    <div class="form-group mt-3">
                        <label asp-for="Descripcion" class="form-label"></label>
                        <textarea asp-for="Descripcion" class="form-control"></textarea>
                        <span asp-validation-for="Descripcion" class="text-danger"></span>
                    </div>
                    <div class="form-group mt-3">
                        <label asp-for="FechaEntrega" class="form-label">Fecha de entrega</label>
                        <input asp-for="FechaEntrega" class="form-control" />
                        <span asp-validation-for="FechaEntrega" class="text-danger"></span>
                    </div>
                    <div class="form-group mt-4 text-center">
                        <input type="submit" value="Añadir tarea" class="btn btn-primary" />
                        <a asp-action="Index" class="btn btn-secondary">Vista principal</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

TareasCompletadas/Views/TaskItem/Delete.cshtml
@model TareasCompletadas.Models.TaskItem

@{
    ViewData["Title"] = "Delete";
}

<div class="container">
    <div class="row">
        <div class="col-12 d-flex justify-content-center align-items-center">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Eliminar Tarea</h5>
                    </div>
                    <div class="modal-body text-center">
                        <p>¿Esta seguro de eliminar la tarea?</p>
                        <i class="bi bi-trash" style="font-size: 5rem; color: red"></i>
                    </div>
                    <div class="modal-footer">
                        <form asp-action="Delete">
                            <a asp-action="Index" type="button" class="btn btn-secondary" >Regresar</a>
                            <input type="hidden" asp-for="Id" />
                            <input type="submit" value="Eliminar" class="btn btn-danger" /> 
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
    
   

TareasCompletadas/Views/TaskItem/Edit.cshtml
@model TareasCompletadas.Models.TaskItem

@{
    ViewData["Title"] = "Edit";
}



<section class="align-items-center">
    <div class="row justify-content-center">
        <div class="col-md-4">
            <div class="card-body p-md-5 mx-md-4 border border-dark rounded">

                <div class="text-center">
                    <i class="bi bi-book" style="font-size: 6rem; color: orange"></i>
                    <h4 class="mt-1 mb-5 pb-1">Editar tarea</h4>
                </div>
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="Id" />
                    <div class="form-group mt-3">
                        <label asp-for="Titulo" class="form-label"></label>
                        <input asp-for="Titulo" class="form-control" />
                        <span asp-validation-for="Titulo" class="text-danger"></span>
                    </div>
                    <div class="form-group mt-3">
                        <label asp-for="Descripcion" class="form-label"></label>
                        <textarea asp-for="Descripcion" class="form-control"></textarea>
                        <span asp-validation-for="Descripcion" class="text-danger"></span>
                    </div>
                    <div class="form-group mt-3">
                        <label asp-for="FechaEntrega" class="form-label">Fecha de entrega</label>
                        <input asp-for="FechaEntrega" class="form-control" />
                        <span asp-validation-for="FechaEntrega" class="text-danger"></span>
                    </div>
                    <div class="form-check form-switch mt-3">
                        <label class="form-check-label">
                            <input class="form-check-input" asp-for="IsCompleted" /> Completada
                        </label>
                    </div>
                    <div class="form-group mt-4 text-center">
                        <input type="submit" value="Guardar" class="btn btn-primary" />
                        <a asp-action="Index" class="btn btn-secondary">Vista principal</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>





@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TareasCompletadas/Views/TaskItem/Historial.cshtml
@model IEnumerable<TareasCompletadas.Models.TaskHistorial>


<div class="container align-items-center">
    <div class="row align-items-start">
        <div class="col border border-3 border-dark rounded m-2">
            <h2 class="text-center">Historial de tareas creadas</h2>
            <div class="row mt-3">
                @foreach (var item in Model)
                {
                    <div class="col-md-6 col-lg-6 col-xl-6 mb-4">
                        <div class="card text-center border border-2 border-primary shadow-0 ">
                            <div class="card-body">
                                <h5 class="card-title">@item.Titulo</h5>
                                <p class="card-text">@item.Descripcion</p>
                                <i class="bi bi-journals" style="font-size: 3rem; color:lawngreen"></i>
                            </div>
                            <div class="card-footer">Fecha limite: @item.FechaEntrega</div>
                            <div class="card-footer" style="color:brown">Fecha de Creacion: @item.FechaCreacion</div>
                        </div>
                    </div>
                }
                <div class="form-group mt-4 text-center" style="margin-bottom:10px">
                    <a asp-action="Index" class="btn btn-secondary">Vista principal</a>
                </div>
            </div>
        </div>
    </div>
</div>

TareasCompletadas/Views/TaskItem/ImprimirPDF.cshtml
@model TareasCompletadas.Models.TaskItem
@{
    ViewData["Title"] = "ImprimirPDF";
    Layout = null;
}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalle de Tarea</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }

        h1 {
            font-size: 24px;
        }

        .tarea-info {
            border: 1px solid #ccc;
            padding: 10px;
            margin-bottom: 20px;
        }

        .label {
            font-weight: bold;
        }
    </style>
</head>
<body>
    <h1>Detalle de Tarea</h1>
    <div class="tarea-info">
        <p class="label">Título:</p>
        <p>@Model.Titulo</p>
    </div>

    <div class="tarea-info">
        <p class="label">Descripción:</p>
        <p>@Model.Descripcion</p>
    </div>

    <div class="tarea-info">
        <p class="label">Fecha de Entrega:</p>
        <p>@Model.FechaEntrega</p>
    </div>

    <div class="tarea-info">
        <p class="label">Estado:</p>
        @if (Model.IsCompleted)
        {
            <p>Completado</p>
        }
        else
        {
            <p>En proceso</p>
        }
    </div>
</body>
</html>

TareasCompletadas/Views/TaskItem/Index.cshtml
@model IEnumerable<TareasCompletadas.Models.TaskItem>

@{
    ViewData["Title"] = "Index";
}
    <a asp-action="Create" class="btn btn-outline-success m-4">Agregar Tarea</a>
    <a asp-action="Historial" class="btn btn-outline-dark">Historial</a>
<div class="container align-items-center">

    <div class="row align-items-start">
        <div class="col border border-3 border-dark rounded m-2">
            <h2 class="text-center">Tareas en proceso</h2>
                <div class="row mt-3">
                    @foreach (var item in ViewBag.TareasIncompletas)
                    {
                        <div class="col-md-6 col-lg-6 col-xl-6 mb-4">
                            <div class="card text-center border border-2 border-primary shadow-0 ">
                                <div class="card-body">
                                    <h5 class="card-title">@item.Titulo</h5>
                                    <p class="card-text">@item.Descripcion</p>
                                    <i class="bi bi-hourglass-split" style="font-size: 3rem; color:slategrey"></i>
                                    <div class="mt-3">
                                        <a asp-controller="TaskItem" asp-action="Edit" asp-route-id="@item.Id" type="button" class="btn btn-primary">Ver</a>
                                        <a asp-controller="TaskItem" asp-action="Delete" asp-route-id="@item.Id" type="button" class="btn btn-danger">Eliminar</a>
                                        <a asp-controller="TaskItem" asp-action="ImprimirPDF" asp-route-id="@item.Id" type="button" class="btn btn-success" style="margin-top:5px">Descargar PDF</a>
                                    </div>
                                </div>
                                <div class="card-footer">Fecha limite: @item.FechaEntrega</div>
                            </div>
                        </div>

                    }
                </div>
        </div>
        <div class="col border border-3 border-dark rounded m-2">
            <h2 class="text-center">Tareas completadas</h2>
            <div class="row mt-3">
                @foreach (var item in ViewBag.TareasCompletadas)
                {
                    <div class="col-md-6 col-lg-6 col-xl-6 mb-4">
                        <div class="card text-center border border-2 border-success shadow-0 ">
                            <div class="card-body">
                                <h5 class="card-title">@item.Titulo</h5>
                                <p class="card-text">@item.Descripcion</p>
                                <i class="bi bi-clipboard-check" style="font-size: 3rem; color:forestgreen"></i>
                                <div class="mt-3">
                                    <a asp-controller="TaskItem" asp-action="Delete" asp-route-id="@item.Id" type="button" class="btn btn-danger">Eliminar</a>
                                    <a asp-controller="TaskItem" asp-action="ImprimirPDF" asp-route-id="@item.Id" type="button" class="btn btn-success">Descargar PDF</a>
                                </div>
                            </div>
                            <div class="card-footer">Entregado: @item.FechaEntrega</div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>